apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      name: http
    - port: 9337
      targetPort: 9337
      protocol: TCP
      name: actuator
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
